import { ChatProvider } from '@ai/contexts/chat-context'
import { LanguageModelProvider } from '@ai/contexts/language-model-context'
import { cn } from '@ai/lib/utils'
import { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import '@ai/app/globals.css'

const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body className={cn(fontHeading.variable, fontBody.variable, 'antialiased')}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ChatProvider>
            <LanguageModelProvider>
              <Toaster />
              {children}
            </LanguageModelProvider>
          </ChatProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
